sudo: false
install: true

language: java

addons:
  sonarcloud:
    organization: "bitgrip"
    token:
      secure: "GaDxVgxW62hzrSIY2kqr/YpjAsxxFLtBGCKPqpFI5dznnTTUTle+E7ngRa2NNRV6wL5Gm3LW+iS7pLcvknzttDWHo/1k8ijMAwg0r7Doah+L4CvsoHH3rBCYahVKMlU3H8L4sWC/sgsP8qJw55jJhqkpJZnYHkttfTdFDnSTdHzI1VteLZWBeE7i1LAO6Fe3ynvjaJ/jhMQt6Cox9mOMd8lHoatsz8CX4T3Po8s4NAPJpQ1EbrEdEuJouTGWdX0Rp1n2butWZUCEKKFffyEGJuHJjPLGBEr/yAVReEKXQGT+sLXNkjjn/MB61eOxChNtXmg1H5WsEL0HhjWO++QmxiCKukxzqcGzzrX1Rmas7BWYLRV1GZLE4SncJ6NOemPjnefsvdtWMA7CyKRJ+AmjCmQUQ76DfDaBg5sBaEil7kabvNuNJ7z0ZCl7I3Uf60GzBl+m4NgVSvPReHEu2oiG5LwAaf7zkCv+bGvi6Ztgcl8+qbbJC5DfvFzsvN5RG+SEel1CMjx1HpiKHXGqhxuKX9LXYY6xMTGep27y+h9bnAG9UszA3Bdf4PVaoOOaBpCudaLBFaOBthgxmy5EW13s8Ckl2x+c2r/iozut8nZTeSA/jOmeW6HrRdIGBLY21hUelS6VMIC/ZxP53he262bH2zq27sZTHXtKbx1FaR39Y1g="

script:
  - mvn clean verify sonar:sonar -Pcoverage -B

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
